name: Check

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Validate presets against renovate schema spec
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NPM Install
        run: npm ci

      - name: Validate
        run: ./.github/scripts/validate.sh
